version: '3'
services:
  rust_mysql:    
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rustpassword
      MYSQL_DATABASE: forexfactory
  rust_phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=1G
      - UPLOAD_LIMIT=1G
