//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "forex_factory_news")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub year: i32,
    pub date: String,
    pub date_line: i32,
    pub actual: String,
    pub country: String,
    pub currency: String,
    pub forecast: String,
    #[sea_orm(column_type = "Text")]
    pub impact_title: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub previous: String,
    pub time_label: String,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    pub timezone: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
